name: Build PicCap with hyperion-webos and create IPK

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build-all:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
        
    - uses: actions/setup-node@v1
      with:
         node-version: 16

    - name: Install webOS CLI
      run: sudo npm install -g @webosose/ares-cli

    - name: Install dependencies
      working-directory: ${{github.workspace}}
      run: npm install
 
    - name: Download webOS NDK
      run: wget -q https://github.com/webosbrew/meta-lg-webos-ndk/releases/download/1.0.g-rev.4/webos-sdk-x86_64-armv7a-neon-toolchain-1.0.g.sh -P ${{github.workspace}}/temp

    - name: Install webOS NDK
      run: chmod 755 ${{github.workspace}}/temp/webos-sdk-x86_64-armv7a-neon-toolchain-1.0.g.sh && sudo ${{github.workspace}}/temp/webos-sdk-x86_64-armv7a-neon-toolchain-1.0.g.sh -y

    - name: Initialize NDK Environments
      run: env -i bash -c '. /opt/webos-sdk-x86_64/1.0.g/environment-setup-armv7a-neon-webos-linux-gnueabi && env' >> $GITHUB_ENV

    - name: Build PicCap, hyperion-webos and copy files
      working-directory: ${{github.workspace}}
      run: npm run-script build-all

    - name: Package Frontend and Service
      run: npm run-script package

    - name: List files
      run: find . && find ./build

    - name: Upload PicCap IPK
      uses: actions/upload-artifact@v2
      with:
        name: piccap_ipk
        path: ./build/*.ipk

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: ./build/*.ipk
